[global]
environment = "development"

[hasura]
version = "v2.33.4"
admin_secret = "your-admin-secret"
jwt_secret = "your-jwt-secret"

[auth]
version = "0.20.0"

[postgres]
version = "14.6-20230406-2"

[storage]
version = "0.3.0"

[functions]
[functions.node]
version = "18"
